// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: Brew Tender v.0.1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void dropdownUserChanged(lv_event_t * e);
void switchPressurizeChanged(lv_event_t * e);
void switchFillChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
