// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: Brew Tender v.1.2

#include "ui.h"

lv_obj_t * uic_sliderPressurize;
lv_obj_t * uic_sliderFill;
lv_obj_t * uic_switchCheckPoint;
lv_obj_t * uic_labelCheckPoint;
lv_obj_t * uic_labelFillLiters;
lv_obj_t * uic_labelFillCm;
lv_obj_t * uic_labelPSI;
lv_obj_t * uic_labelFill;
lv_obj_t * uic_labelPressurize;
lv_obj_t * uic_switchFill;
lv_obj_t * uic_switchPressurize;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_switchPressurize = NULL;
lv_obj_t * ui_switchFill = NULL;
lv_obj_t * ui_labelPressurize = NULL;
lv_obj_t * ui_labelFill = NULL;
lv_obj_t * ui_labelPSI = NULL;
lv_obj_t * ui_labelFillCm = NULL;
lv_obj_t * ui_labelFillLiters = NULL;
lv_obj_t * ui_labelCheckPoint = NULL;
lv_obj_t * ui_switchCheckPoint = NULL;
lv_obj_t * ui_dropdownUser = NULL;
lv_obj_t * ui_sliderFill = NULL;
lv_obj_t * ui_sliderPressurize = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_switchPressurize(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchPressurizeChanged(e);
    }
}

void ui_event_switchFill(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchFillChanged(e);
    }
}

void ui_event_dropdownUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dropdownUserChanged(e);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Home);
    lv_image_set_src(ui_Image1, &ui_img_possum_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 393
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 412
    lv_obj_set_x(ui_Image1, 16);
    lv_obj_set_y(ui_Image1, -1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switchPressurize = lv_switch_create(ui_Home);
    lv_obj_set_width(ui_switchPressurize, 92);
    lv_obj_set_height(ui_switchPressurize, 46);
    lv_obj_set_x(ui_switchPressurize, -294);
    lv_obj_set_y(ui_switchPressurize, -24);
    lv_obj_set_align(ui_switchPressurize, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switchPressurize, lv_color_hex(0xFF7173), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchPressurize, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_switchPressurize, lv_color_hex(0x9C2841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_switchPressurize, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchFill = lv_switch_create(ui_Home);
    lv_obj_set_width(ui_switchFill, 95);
    lv_obj_set_height(ui_switchFill, 47);
    lv_obj_set_x(ui_switchFill, -293);
    lv_obj_set_y(ui_switchFill, 128);
    lv_obj_set_align(ui_switchFill, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_switchFill, lv_color_hex(0x00E9FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_switchFill, lv_color_hex(0x6693F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_switchFill, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPressurize = lv_label_create(ui_Home);
    lv_obj_set_width(ui_labelPressurize, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPressurize, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPressurize, -298);
    lv_obj_set_y(ui_labelPressurize, -78);
    lv_obj_set_align(ui_labelPressurize, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPressurize, "Pressurize");
    lv_obj_set_style_text_font(ui_labelPressurize, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelFill = lv_label_create(ui_Home);
    lv_obj_set_width(ui_labelFill, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFill, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFill, -327);
    lv_obj_set_y(ui_labelFill, 76);
    lv_obj_set_align(ui_labelFill, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFill, "Fill");
    lv_obj_set_style_text_font(ui_labelFill, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPSI = lv_label_create(ui_Home);
    lv_obj_set_width(ui_labelPSI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPSI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPSI, -193);
    lv_obj_set_y(ui_labelPSI, -21);
    lv_obj_set_align(ui_labelPSI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelPSI, "PSI");

    ui_labelFillCm = lv_label_create(ui_Home);
    lv_obj_set_width(ui_labelFillCm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFillCm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFillCm, -185);
    lv_obj_set_y(ui_labelFillCm, 122);
    lv_obj_set_align(ui_labelFillCm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFillCm, "cm");

    ui_labelFillLiters = lv_label_create(ui_Home);
    lv_obj_set_width(ui_labelFillLiters, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelFillLiters, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelFillLiters, -181);
    lv_obj_set_y(ui_labelFillLiters, 148);
    lv_obj_set_align(ui_labelFillLiters, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelFillLiters, "liters");

    ui_labelCheckPoint = lv_label_create(ui_Home);
    lv_obj_set_width(ui_labelCheckPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCheckPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCheckPoint, 314);
    lv_obj_set_y(ui_labelCheckPoint, -208);
    lv_obj_set_align(ui_labelCheckPoint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCheckPoint, "Check Point");

    ui_switchCheckPoint = lv_switch_create(ui_Home);
    lv_obj_set_width(ui_switchCheckPoint, 50);
    lv_obj_set_height(ui_switchCheckPoint, 25);
    lv_obj_set_x(ui_switchCheckPoint, 298);
    lv_obj_set_y(ui_switchCheckPoint, -179);
    lv_obj_set_align(ui_switchCheckPoint, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_switchCheckPoint, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_switchCheckPoint, lv_color_hex(0x9C2841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switchCheckPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropdownUser = lv_dropdown_create(ui_Home);
    lv_dropdown_set_options(ui_dropdownUser, "User...\nJennie\nAlex");
    lv_obj_set_width(ui_dropdownUser, 150);
    lv_obj_set_height(ui_dropdownUser, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropdownUser, -289);
    lv_obj_set_y(ui_dropdownUser, -201);
    lv_obj_set_align(ui_dropdownUser, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropdownUser, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_sliderFill = lv_slider_create(ui_Home);
    lv_slider_set_value(ui_sliderFill, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sliderFill) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_sliderFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sliderFill, 150);
    lv_obj_set_height(ui_sliderFill, 10);
    lv_obj_set_x(ui_sliderFill, -266);
    lv_obj_set_y(ui_sliderFill, 178);
    lv_obj_set_align(ui_sliderFill, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_sliderFill, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_sliderFill, lv_color_hex(0x6693F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sliderFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sliderFill, lv_color_hex(0x00E9FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sliderFill, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sliderFill, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sliderFill,
                                                                                                 lv_obj_get_style_pad_right(ui_sliderFill, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_sliderPressurize = lv_slider_create(ui_Home);
    lv_slider_set_value(ui_sliderPressurize, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sliderPressurize) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_sliderPressurize, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_sliderPressurize, 150);
    lv_obj_set_height(ui_sliderPressurize, 10);
    lv_obj_set_x(ui_sliderPressurize, -266);
    lv_obj_set_y(ui_sliderPressurize, 23);
    lv_obj_set_align(ui_sliderPressurize, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_sliderPressurize, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_bg_color(ui_sliderPressurize, lv_color_hex(0x9C2841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sliderPressurize, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sliderPressurize, lv_color_hex(0xFF7173), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sliderPressurize, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sliderPressurize, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sliderPressurize,
                                                                                                       lv_obj_get_style_pad_right(ui_sliderPressurize, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image2 = lv_image_create(ui_Home);
    lv_image_set_src(ui_Image2, &ui_img_1324469499);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_Image2, 351);
    lv_obj_set_y(ui_Image2, 196);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_switchPressurize, ui_event_switchPressurize, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchFill, ui_event_switchFill, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropdownUser, ui_event_dropdownUser, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_switchPressurize = ui_switchPressurize;
    uic_switchFill = ui_switchFill;
    uic_labelPressurize = ui_labelPressurize;
    uic_labelFill = ui_labelFill;
    uic_labelPSI = ui_labelPSI;
    uic_labelFillCm = ui_labelFillCm;
    uic_labelFillLiters = ui_labelFillLiters;
    uic_labelCheckPoint = ui_labelCheckPoint;
    uic_switchCheckPoint = ui_switchCheckPoint;
    uic_sliderFill = ui_sliderFill;
    uic_sliderPressurize = ui_sliderPressurize;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    ui_Image1 = NULL;
    uic_switchPressurize = NULL;
    ui_switchPressurize = NULL;
    uic_switchFill = NULL;
    ui_switchFill = NULL;
    uic_labelPressurize = NULL;
    ui_labelPressurize = NULL;
    uic_labelFill = NULL;
    ui_labelFill = NULL;
    uic_labelPSI = NULL;
    ui_labelPSI = NULL;
    uic_labelFillCm = NULL;
    ui_labelFillCm = NULL;
    uic_labelFillLiters = NULL;
    ui_labelFillLiters = NULL;
    uic_labelCheckPoint = NULL;
    ui_labelCheckPoint = NULL;
    uic_switchCheckPoint = NULL;
    ui_switchCheckPoint = NULL;
    ui_dropdownUser = NULL;
    uic_sliderFill = NULL;
    ui_sliderFill = NULL;
    uic_sliderPressurize = NULL;
    ui_sliderPressurize = NULL;
    ui_Image2 = NULL;

}
