// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: Brew Tender v.1.2

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Image1;
extern void ui_event_switchPressurize(lv_event_t * e);
extern lv_obj_t * ui_switchPressurize;
extern void ui_event_switchFill(lv_event_t * e);
extern lv_obj_t * ui_switchFill;
extern lv_obj_t * ui_labelPressurize;
extern lv_obj_t * ui_labelFill;
extern lv_obj_t * ui_labelPSI;
extern lv_obj_t * ui_labelFillCm;
extern lv_obj_t * ui_labelFillLiters;
extern lv_obj_t * ui_labelCheckPoint;
extern lv_obj_t * ui_switchCheckPoint;
extern void ui_event_dropdownUser(lv_event_t * e);
extern lv_obj_t * ui_dropdownUser;
extern lv_obj_t * ui_sliderFill;
extern lv_obj_t * ui_sliderPressurize;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home;
extern lv_obj_t * uic_switchPressurize;
extern lv_obj_t * uic_switchFill;
extern lv_obj_t * uic_labelPressurize;
extern lv_obj_t * uic_labelFill;
extern lv_obj_t * uic_labelPSI;
extern lv_obj_t * uic_labelFillCm;
extern lv_obj_t * uic_labelFillLiters;
extern lv_obj_t * uic_labelCheckPoint;
extern lv_obj_t * uic_switchCheckPoint;
extern lv_obj_t * uic_sliderFill;
extern lv_obj_t * uic_sliderPressurize;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

