// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Brew Tender v.1.2

#include "../ui.h"

// COMPONENT Switch1

lv_obj_t * ui_Switch1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Switch1;
    cui_Switch1 = lv_switch_create(comp_parent);
    lv_obj_set_width(cui_Switch1, 50);
    lv_obj_set_height(cui_Switch1, 25);
    lv_obj_set_x(cui_Switch1, -253);
    lv_obj_set_y(cui_Switch1, -18);
    lv_obj_set_align(cui_Switch1, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SWITCH1_NUM);
    children[UI_COMP_SWITCH1_SWITCH1] = cui_Switch1;
    lv_obj_add_event_cb(cui_Switch1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Switch1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Switch1_create_hook(cui_Switch1);
    return cui_Switch1;
}

