// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Brew Tender v.1.2

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern void ui_event_switchPressurize(lv_event_t * e);
extern lv_obj_t * ui_switchPressurize;
extern void ui_event_switchFill(lv_event_t * e);
extern lv_obj_t * ui_switchFill;
// CUSTOM VARIABLES
extern lv_obj_t * uic_switchPressurize;
extern lv_obj_t * uic_switchFill;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

