// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: Brew Tender v.1.2

#include "ui.h"

void switchPressurizeChanged(lv_event_t * e)
{
	// Your code here
}

void switchFillChanged(lv_event_t * e)
{
	// Your code here
}
