// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Brew Tender v.1.2

#include "../ui.h"

lv_obj_t * uic_switchFill;
lv_obj_t * uic_switchPressurize;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_switchPressurize = NULL;
lv_obj_t * ui_switchFill = NULL;
// event funtions
void ui_event_switchPressurize(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchPressurizeChanged(e);
    }
}

void ui_event_switchFill(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switchFillChanged(e);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Home);
    lv_image_set_src(ui_Image1, &ui_img_possum_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 393
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 412
    lv_obj_set_x(ui_Image1, 16);
    lv_obj_set_y(ui_Image1, -1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_switchPressurize = lv_switch_create(ui_Home);
    lv_obj_set_width(ui_switchPressurize, 95);
    lv_obj_set_height(ui_switchPressurize, 65);
    lv_obj_set_x(ui_switchPressurize, -299);
    lv_obj_set_y(ui_switchPressurize, -18);
    lv_obj_set_align(ui_switchPressurize, LV_ALIGN_CENTER);

    ui_switchFill = lv_switch_create(ui_Home);
    lv_obj_set_width(ui_switchFill, 95);
    lv_obj_set_height(ui_switchFill, 65);
    lv_obj_set_x(ui_switchFill, -294);
    lv_obj_set_y(ui_switchFill, 113);
    lv_obj_set_align(ui_switchFill, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_switchPressurize, ui_event_switchPressurize, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchFill, ui_event_switchFill, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_switchPressurize = ui_switchPressurize;
    uic_switchFill = ui_switchFill;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    ui_Image1 = NULL;
    uic_switchPressurize = NULL;
    ui_switchPressurize = NULL;
    uic_switchFill = NULL;
    ui_switchFill = NULL;

}
